### ISSUE TITLE
Build failed on RN version 0.69-rc.5

### ISSUE THREAD

**Issue by AlirezaHadjar** [th3rdwave/react-native-safe-area-context#285]
I've been testing the rc version of react-native. and when it comes to compiling react-native-safe-area-context, it failed with the following error:

> Task :react-native-safe-area-context:configureNdkBuildDebug[arm64-v8a] FAILED
C/C++: fcntl(): Bad file descriptor
C/C++: /Users/alirezahadjar/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:651: Android NDK: Module safeareacontext_common depends on undefined modules: folly_json    
C/C++: /Users/alirezahadjar/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:664: *** Android NDK: Note that old versions of ndk-build silently ignored this error case. If your project worked on those versions, the missing libraries were not needed and you can remove those dependencies from the module to fix your build. Alternatively, set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies.    .  Stop.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
293 actionable tasks: 28 executed, 265 up-to-date
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-safe-area-context:configureNdkBuildDebug[arm64-v8a]'.
> [CXX1405] error when building with ndkBuild using /Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/react-native-safe-area-context/android/src/main/jni/Android.mk: Build command failed.
  Error while executing process /Users/alirezahadjar/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/react-native-safe-area-context/android/src/main/jni/Android.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 NDK_OUT=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/react-native-safe-area-context/android/build/intermediates/cxx/Debug/h164o1d7/obj NDK_LIBS_OUT=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/react-native-safe-area-context/android/build/intermediates/cxx/Debug/h164o1d7/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/android/app/build REACT_ANDROID_DIR=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/android/../node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/android/../node_modules/react-native/ReactAndroid/build APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
  
  fcntl(): Bad file descriptor
  /Users/alirezahadjar/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:651: Android NDK: Module safeareacontext_common depends on undefined modules: folly_json    
  /Users/alirezahadjar/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:664: *** Android NDK: Note that old versions of ndk-build silently ignored this error case. If your project worked on those versions, the missing libraries were not needed and you can remove those dependencies from the module to fix your build. Alternatively, set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies.    .  Stop.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 35s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-safe-area-context:configureNdkBuildDebug[arm64-v8a]'.
> [CXX1405] error when building with ndkBuild using /Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/react-native-safe-area-context/android/src/main/jni/Android.mk: Build command failed.
  Error while executing process /Users/alirezahadjar/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/react-native-safe-area-context/android/src/main/jni/Android.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 NDK_OUT=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/react-native-safe-area-context/android/build/intermediates/cxx/Debug/h164o1d7/obj NDK_LIBS_OUT=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/react-native-safe-area-context/android/build/intermediates/cxx/Debug/h164o1d7/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/android/app/build REACT_ANDROID_DIR=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/android/../node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/android/../node_modules/react-native/ReactAndroid/build APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
  
  fcntl(): Bad file descriptor
  /Users/alirezahadjar/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:651: Android NDK: Module safeareacontext_common depends on undefined modules: folly_json    
  /Users/alirezahadjar/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:664: *** Android NDK: Note that old versions of ndk-build silently ignored this error case. If your project worked on those versions, the missing libraries were not needed and you can remove those dependencies from the module to fix your build. Alternatively, set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies.    .  Stop.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 35s

    at makeError (/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/execa/index.js:174:9)
    at /Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/alirezahadjar/Dropbox/Mac/Desktop/Projects/ReactNative/Charlatan/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by janicduplessis** [comment]
Latest version should work with 0.69 now!

**Comment by AlirezaHadjar** [comment]
I've been using the latest version though.

**Comment by janicduplessis** [comment]
It should be fixed in version 4.3.1 that I published yesterday, is that the version you have?

**Comment by AlirezaHadjar** [comment]
My bad, I've been checking the release page. 
Thank you for the fix.

**Comment by MLawlz** [comment]
Want to follow up here and say I'm running into the same issue on 4.3.1. I can see that you require `folly_runtime` in `android/src/main/jni/Android.mk`, but it still fails to build every time.

**Comment by janicduplessis** [comment]
@MLawlz what version of react native are you using? I think the new architecture implementation only supports 0.69 with the changes I made. Will keep targeting latest RC for now until it stabilizes.

**Comment by MLawlz** [comment]
On 0.68.2 at the moment.

**Comment by whalemare** [comment]
Same, on react-native 0.68.2 each build crashed because 

```
> Task :app:configureNdkBuildDebug FAILED
C/C++: fcntl(): Bad file descriptor
C/C++: /Users/user/Library/Android/sdk/ndk/24.0.8215888/build/core/build-binary.mk:586: Android NDK: Module app_appmodules depends on undefined modules: folly_runtime 
```

**Comment by AlirezaHadjar** [comment]
> Same, on react-native 0.68.2 each build crashed because
> 
> ```
> > Task :app:configureNdkBuildDebug FAILED
> C/C++: fcntl(): Bad file descriptor
> C/C++: /Users/user/Library/Android/sdk/ndk/24.0.8215888/build/core/build-binary.mk:586: Android NDK: Module app_appmodules depends on undefined modules: folly_runtime 
> ```

You can check the [commit](https://github.com/th3rdwave/react-native-safe-area-context/commit/24de83324be978c5575579d0e08b4be143a791e1#diff-f2a904498cde17421e687e9b7b2b2f73db2f88940ac791ab82ce62ad869cb092) that fixes this issue for 0.69 and do the steps manually until it gets fixed. 

Note: only apply changes on these three files: 
- android/build.gradle
- android/src/main/jni/Android.mk
- common/cpp/Android.mk

**Comment by ShaoGongBra** [comment]
我也是0.68.2，有什么解决办法吗
