### ISSUE TITLE
[RN 0.70.0-rc.2] newArchEnabled `android/src/main/jni/Android.mk:fb` LOCAL_SRC_FILES points to a missing file

### ISSUE THREAD

**Issue by leotm** [th3rdwave/react-native-safe-area-context#303]
`react-native-safe-area-context` builds fine w `newArchEnabled=false` but fails w `newArchEnabled=true`

Context
- https://github.com/reactwg/react-native-releases/discussions/26#discussioncomment-3327849

Repro
- https://github.com/leotm/react-native-template-new-architecture/pull/842

Repro (minimal)
- https://github.com/leotm/RN070RC2

_Can also repro locally on macOS 13b_

**Comment by tomekzaw** [comment]
Hey, we @software-mansion also encounter this issue with our libs (and in fact this started to break our CI builds since 0.70.0-rc.2). The error originates from a custom Android.mk used for autolinking introduced in this PR by @kmagiera: https://github.com/software-mansion/react-native-screens/pull/1322. Basically, `libfb.so` does not exit when Android NDK configures the build and that's why it fails.

**Fun fact:** it works on the second build, because `libfb.so` has already been built.

To overcome this issue, we decided to use the new autolinking mechanism by @thymikee introduced in 0.70.0-rc.3 and also migrate towards using CMake instead of Android NDK. As a result, we will drop Fabric support for 0.68 and 0.69 in the next release. This already works fine in RNGH (see the PR: https://github.com/software-mansion/react-native-gesture-handler/pull/2153). The CI still fails because we use RNScreens & RNSafeAreaContext in our FabricExample, but without these two it builds successfully.

@janicduplessis When do you plan to migrate RNSafeAreaContext to RN 0.70? Do you think it's possible to drop support for 0.68 and 0.69 and migrate towards autolinking & CMake just as we do? If you don't have free time, I think I can submit a PR analogous to the one in RNGH.

**Comment by janicduplessis** [comment]
Hey @tomekzaw, I'm actually working on upgrading to 0.70 today, for fabric I decided to only support latest RC version so I'm fine with dropping support for 0.68/69.

**Comment by MLawlz** [comment]
@janicduplessis Any word on the upgrade to 0.70? I'm happy to assist to get it taken care of since this issue is currently blocking our team from using the new architecture.

**Comment by janicduplessis** [comment]
Sorry about the delay on this, I didn't have time to finish the update when I worked on it. I just pushed the work I got done here https://github.com/th3rdwave/react-native-safe-area-context/tree/update-rn, if I remember correctly iOS works and android is left to finish. Feel free to pick it up as I don't think I will have time to finish this until 1-2 weeks.

**Comment by allemanfredi** [comment]
@janicduplessis I'm using RN 0.70.0 but i still have the issue. Is it normal?

**Comment by ugurdalkiran** [comment]
Any progress?

**Comment by janicduplessis** [comment]
Fixed in 4.4.0 which supports RN 0.70.0

**Comment by ugurdalkiran** [comment]
Thanks. @tido64 @janicduplessis 🤩🤩
